inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/EmptyClass:
  Enabled: false

Metrics/AbcSize:
  Max: 50
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - test/**/*
    - lib/tasks/*

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Max: 25
  Exclude:
    - test/**/*

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
